apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-certificates
spec:
  params:
  - name: REVISION
    default: main
  workspaces:
  - name: source
  tasks:
  - name: use-image
    taskSpec:
      steps:
      - name: run
        image: quay.io/ppitonak/certificate-test:211210t
        script: |
          #!/usr/bin/env bash
          #set -e
          echo "SSL_CERT_DIR: $SSL_CERT_DIR"
          
          echo -e "\n\nhttp-client: gitlab"
          http-client https://gitlab.cee.redhat.com/tekton/plumbing/-/raw/master/ci/secrets/polarion.yaml
          
          echo -e "\n\nhttp-client: API server"
          http-client https://api.cicd.tekton.codereadyqe.com:6443/version
          
          echo -e "\n\ncurl: gitlab"
          curl https://gitlab.cee.redhat.com/tekton/plumbing/-/raw/master/ci/secrets/polarion.yaml

          echo -e "\n\ncurl: API server"
          curl https://api.cicd.tekton.codereadyqe.com:6443/version
